name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        working-directory: ./react
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./react
        run: npm ci

      - name: Build
        working-directory: ./react
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        working-directory: ./react
        with:
          folder: build
          branch: gh-pages