name: Extract metadata and upload to S3

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      S3_BUCKET: linc-dashboard

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Run Python script
      env:
        DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}
      run: python extract-metadata.py

    - name: Upload CSV files to S3
      run: |
        aws s3 cp *.csv s3://${{ env.S3_BUCKET }}/
